// Mocks generated by Mockito from annotations
// in m3_pad/test/src/features/voucher/domain/usecases/add_row_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i6;

import 'package:m3_pad/src/core/utils/id_generator.dart' as _i9;
import 'package:m3_pad/src/features/voucher/domain/entities/customer.dart'
    as _i2;
import 'package:m3_pad/src/features/voucher/domain/entities/sheet_row.dart'
    as _i4;
import 'package:m3_pad/src/features/voucher/domain/entities/staff.dart' as _i3;
import 'package:m3_pad/src/features/voucher/domain/repositories/customer_repository.dart'
    as _i5;
import 'package:m3_pad/src/features/voucher/domain/repositories/sheet_row_repository.dart'
    as _i8;
import 'package:m3_pad/src/features/voucher/domain/repositories/staff_repository.dart'
    as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i10;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: experimental_member_use
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeCustomer_0 extends _i1.SmartFake implements _i2.Customer {
  _FakeCustomer_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStaff_1 extends _i1.SmartFake implements _i3.Staff {
  _FakeStaff_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSheetRow_2 extends _i1.SmartFake implements _i4.SheetRow {
  _FakeSheetRow_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [CustomerRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCustomerRepository extends _i1.Mock
    implements _i5.CustomerRepository {
  @override
  _i6.Future<void> insert(_i2.Customer? customer) => (super.noSuchMethod(
        Invocation.method(
          #insert,
          [customer],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i2.Customer> findById(String? customerId) => (super.noSuchMethod(
        Invocation.method(
          #findById,
          [customerId],
        ),
        returnValue: _i6.Future<_i2.Customer>.value(_FakeCustomer_0(
          this,
          Invocation.method(
            #findById,
            [customerId],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i2.Customer>.value(_FakeCustomer_0(
          this,
          Invocation.method(
            #findById,
            [customerId],
          ),
        )),
      ) as _i6.Future<_i2.Customer>);

  @override
  _i6.Future<List<_i2.Customer>> findByIds(List<String>? customerIds) =>
      (super.noSuchMethod(
        Invocation.method(
          #findByIds,
          [customerIds],
        ),
        returnValue: _i6.Future<List<_i2.Customer>>.value(<_i2.Customer>[]),
        returnValueForMissingStub:
            _i6.Future<List<_i2.Customer>>.value(<_i2.Customer>[]),
      ) as _i6.Future<List<_i2.Customer>>);
}

/// A class which mocks [StaffRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockStaffRepository extends _i1.Mock implements _i7.StaffRepository {
  @override
  _i6.Future<_i3.Staff> findById(String? staffId) => (super.noSuchMethod(
        Invocation.method(
          #findById,
          [staffId],
        ),
        returnValue: _i6.Future<_i3.Staff>.value(_FakeStaff_1(
          this,
          Invocation.method(
            #findById,
            [staffId],
          ),
        )),
        returnValueForMissingStub: _i6.Future<_i3.Staff>.value(_FakeStaff_1(
          this,
          Invocation.method(
            #findById,
            [staffId],
          ),
        )),
      ) as _i6.Future<_i3.Staff>);

  @override
  _i6.Future<List<_i3.Staff>> findAllActive() => (super.noSuchMethod(
        Invocation.method(
          #findAllActive,
          [],
        ),
        returnValue: _i6.Future<List<_i3.Staff>>.value(<_i3.Staff>[]),
        returnValueForMissingStub:
            _i6.Future<List<_i3.Staff>>.value(<_i3.Staff>[]),
      ) as _i6.Future<List<_i3.Staff>>);
}

/// A class which mocks [SheetRowRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSheetRowRepository extends _i1.Mock
    implements _i8.SheetRowRepository {
  @override
  _i6.Future<void> insert(_i4.SheetRow? row) => (super.noSuchMethod(
        Invocation.method(
          #insert,
          [row],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> update(_i4.SheetRow? row) => (super.noSuchMethod(
        Invocation.method(
          #update,
          [row],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i4.SheetRow> findById(String? rowId) => (super.noSuchMethod(
        Invocation.method(
          #findById,
          [rowId],
        ),
        returnValue: _i6.Future<_i4.SheetRow>.value(_FakeSheetRow_2(
          this,
          Invocation.method(
            #findById,
            [rowId],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i4.SheetRow>.value(_FakeSheetRow_2(
          this,
          Invocation.method(
            #findById,
            [rowId],
          ),
        )),
      ) as _i6.Future<_i4.SheetRow>);

  @override
  _i6.Future<int> findMaxRowOrder(String? sheetInstanceId) =>
      (super.noSuchMethod(
        Invocation.method(
          #findMaxRowOrder,
          [sheetInstanceId],
        ),
        returnValue: _i6.Future<int>.value(0),
        returnValueForMissingStub: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);

  @override
  _i6.Future<List<_i4.SheetRow>> findByInstanceId(String? sheetInstanceId) =>
      (super.noSuchMethod(
        Invocation.method(
          #findByInstanceId,
          [sheetInstanceId],
        ),
        returnValue: _i6.Future<List<_i4.SheetRow>>.value(<_i4.SheetRow>[]),
        returnValueForMissingStub:
            _i6.Future<List<_i4.SheetRow>>.value(<_i4.SheetRow>[]),
      ) as _i6.Future<List<_i4.SheetRow>>);
}

/// A class which mocks [IdGenerator].
///
/// See the documentation for Mockito's code generation for more information.
class MockIdGenerator extends _i1.Mock implements _i9.IdGenerator {
  @override
  String generate() => (super.noSuchMethod(
        Invocation.method(
          #generate,
          [],
        ),
        returnValue: _i10.dummyValue<String>(
          this,
          Invocation.method(
            #generate,
            [],
          ),
        ),
        returnValueForMissingStub: _i10.dummyValue<String>(
          this,
          Invocation.method(
            #generate,
            [],
          ),
        ),
      ) as String);
}
