// Mocks generated by Mockito from annotations
// in m3_pad/test/src/features/voucher/domain/usecases/add_staff_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i4;

import 'package:m3_pad/src/core/utils/id_generator.dart' as _i6;
import 'package:m3_pad/src/features/voucher/domain/entities/enums/enums.dart'
    as _i5;
import 'package:m3_pad/src/features/voucher/domain/entities/staff.dart' as _i2;
import 'package:m3_pad/src/features/voucher/domain/repositories/staff_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: experimental_member_use
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeStaff_0 extends _i1.SmartFake implements _i2.Staff {
  _FakeStaff_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [StaffRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockStaffRepository extends _i1.Mock implements _i3.StaffRepository {
  @override
  _i4.Future<void> insert(_i2.Staff? staff) => (super.noSuchMethod(
        Invocation.method(
          #insert,
          [staff],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i2.Staff> findById(String? staffId) => (super.noSuchMethod(
        Invocation.method(
          #findById,
          [staffId],
        ),
        returnValue: _i4.Future<_i2.Staff>.value(_FakeStaff_0(
          this,
          Invocation.method(
            #findById,
            [staffId],
          ),
        )),
        returnValueForMissingStub: _i4.Future<_i2.Staff>.value(_FakeStaff_0(
          this,
          Invocation.method(
            #findById,
            [staffId],
          ),
        )),
      ) as _i4.Future<_i2.Staff>);

  @override
  _i4.Future<List<_i2.Staff>> findAllActive() => (super.noSuchMethod(
        Invocation.method(
          #findAllActive,
          [],
        ),
        returnValue: _i4.Future<List<_i2.Staff>>.value(<_i2.Staff>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i2.Staff>>.value(<_i2.Staff>[]),
      ) as _i4.Future<List<_i2.Staff>>);

  @override
  _i4.Future<_i2.Staff?> findByName(String? name) => (super.noSuchMethod(
        Invocation.method(
          #findByName,
          [name],
        ),
        returnValue: _i4.Future<_i2.Staff?>.value(),
        returnValueForMissingStub: _i4.Future<_i2.Staff?>.value(),
      ) as _i4.Future<_i2.Staff?>);

  @override
  _i4.Future<void> updateName(
    String? staffId,
    String? name,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateName,
          [
            staffId,
            name,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateStatus(
    String? staffId,
    _i5.RecordStatus? status,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateStatus,
          [
            staffId,
            status,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [IdGenerator].
///
/// See the documentation for Mockito's code generation for more information.
class MockIdGenerator extends _i1.Mock implements _i6.IdGenerator {
  @override
  String generate() => (super.noSuchMethod(
        Invocation.method(
          #generate,
          [],
        ),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.method(
            #generate,
            [],
          ),
        ),
        returnValueForMissingStub: _i7.dummyValue<String>(
          this,
          Invocation.method(
            #generate,
            [],
          ),
        ),
      ) as String);
}
