// Mocks generated by Mockito from annotations
// in m3_pad/test/src/features/voucher/domain/usecases/create_template_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i4;

import 'package:m3_pad/src/core/utils/id_generator.dart' as _i5;
import 'package:m3_pad/src/features/voucher/domain/entities/sheet_template.dart'
    as _i2;
import 'package:m3_pad/src/features/voucher/domain/repositories/sheet_template_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: experimental_member_use
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSheetTemplate_0 extends _i1.SmartFake implements _i2.SheetTemplate {
  _FakeSheetTemplate_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SheetTemplateRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSheetTemplateRepository extends _i1.Mock
    implements _i3.SheetTemplateRepository {
  @override
  _i4.Future<void> insert(_i2.SheetTemplate? template) => (super.noSuchMethod(
        Invocation.method(
          #insert,
          [template],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i2.SheetTemplate> findById(String? sheetTemplateId) =>
      (super.noSuchMethod(
        Invocation.method(
          #findById,
          [sheetTemplateId],
        ),
        returnValue: _i4.Future<_i2.SheetTemplate>.value(_FakeSheetTemplate_0(
          this,
          Invocation.method(
            #findById,
            [sheetTemplateId],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.SheetTemplate>.value(_FakeSheetTemplate_0(
          this,
          Invocation.method(
            #findById,
            [sheetTemplateId],
          ),
        )),
      ) as _i4.Future<_i2.SheetTemplate>);

  @override
  _i4.Future<List<_i2.SheetTemplate>> findAllActive() => (super.noSuchMethod(
        Invocation.method(
          #findAllActive,
          [],
        ),
        returnValue:
            _i4.Future<List<_i2.SheetTemplate>>.value(<_i2.SheetTemplate>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i2.SheetTemplate>>.value(<_i2.SheetTemplate>[]),
      ) as _i4.Future<List<_i2.SheetTemplate>>);
}

/// A class which mocks [IdGenerator].
///
/// See the documentation for Mockito's code generation for more information.
class MockIdGenerator extends _i1.Mock implements _i5.IdGenerator {
  @override
  String generate() => (super.noSuchMethod(
        Invocation.method(
          #generate,
          [],
        ),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.method(
            #generate,
            [],
          ),
        ),
        returnValueForMissingStub: _i6.dummyValue<String>(
          this,
          Invocation.method(
            #generate,
            [],
          ),
        ),
      ) as String);
}
