// Mocks generated by Mockito from annotations
// in m3_pad/test/src/features/voucher/domain/usecases/export_daily_sheet_to_csv_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i6;

import 'package:m3_pad/src/features/voucher/domain/entities/enums/enums.dart'
    as _i8;
import 'package:m3_pad/src/features/voucher/domain/entities/header.dart' as _i3;
import 'package:m3_pad/src/features/voucher/domain/entities/sheet_cell.dart'
    as _i11;
import 'package:m3_pad/src/features/voucher/domain/entities/sheet_instance.dart'
    as _i2;
import 'package:m3_pad/src/features/voucher/domain/entities/sheet_row.dart'
    as _i4;
import 'package:m3_pad/src/features/voucher/domain/repositories/header_repository.dart'
    as _i7;
import 'package:m3_pad/src/features/voucher/domain/repositories/sheet_cell_repository.dart'
    as _i10;
import 'package:m3_pad/src/features/voucher/domain/repositories/sheet_instance_repository.dart'
    as _i5;
import 'package:m3_pad/src/features/voucher/domain/repositories/sheet_row_repository.dart'
    as _i9;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: experimental_member_use
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSheetInstance_0 extends _i1.SmartFake implements _i2.SheetInstance {
  _FakeSheetInstance_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeHeader_1 extends _i1.SmartFake implements _i3.Header {
  _FakeHeader_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSheetRow_2 extends _i1.SmartFake implements _i4.SheetRow {
  _FakeSheetRow_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SheetInstanceRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSheetInstanceRepository extends _i1.Mock
    implements _i5.SheetInstanceRepository {
  @override
  _i6.Future<void> insert(_i2.SheetInstance? instance) => (super.noSuchMethod(
        Invocation.method(
          #insert,
          [instance],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i2.SheetInstance> findById(String? sheetInstanceId) =>
      (super.noSuchMethod(
        Invocation.method(
          #findById,
          [sheetInstanceId],
        ),
        returnValue: _i6.Future<_i2.SheetInstance>.value(_FakeSheetInstance_0(
          this,
          Invocation.method(
            #findById,
            [sheetInstanceId],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i2.SheetInstance>.value(_FakeSheetInstance_0(
          this,
          Invocation.method(
            #findById,
            [sheetInstanceId],
          ),
        )),
      ) as _i6.Future<_i2.SheetInstance>);

  @override
  _i6.Future<_i2.SheetInstance?> findByTemplateAndDate(
    String? sheetTemplateId,
    DateTime? businessDate,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #findByTemplateAndDate,
          [
            sheetTemplateId,
            businessDate,
          ],
        ),
        returnValue: _i6.Future<_i2.SheetInstance?>.value(),
        returnValueForMissingStub: _i6.Future<_i2.SheetInstance?>.value(),
      ) as _i6.Future<_i2.SheetInstance?>);
}

/// A class which mocks [HeaderRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockHeaderRepository extends _i1.Mock implements _i7.HeaderRepository {
  @override
  _i6.Future<void> insert(_i3.Header? header) => (super.noSuchMethod(
        Invocation.method(
          #insert,
          [header],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i3.Header> findById(String? columnId) => (super.noSuchMethod(
        Invocation.method(
          #findById,
          [columnId],
        ),
        returnValue: _i6.Future<_i3.Header>.value(_FakeHeader_1(
          this,
          Invocation.method(
            #findById,
            [columnId],
          ),
        )),
        returnValueForMissingStub: _i6.Future<_i3.Header>.value(_FakeHeader_1(
          this,
          Invocation.method(
            #findById,
            [columnId],
          ),
        )),
      ) as _i6.Future<_i3.Header>);

  @override
  _i6.Future<List<_i3.Header>> findByTemplateId(String? sheetTemplateId) =>
      (super.noSuchMethod(
        Invocation.method(
          #findByTemplateId,
          [sheetTemplateId],
        ),
        returnValue: _i6.Future<List<_i3.Header>>.value(<_i3.Header>[]),
        returnValueForMissingStub:
            _i6.Future<List<_i3.Header>>.value(<_i3.Header>[]),
      ) as _i6.Future<List<_i3.Header>>);

  @override
  _i6.Future<void> updateDisplayOrders(
          Map<String, int>? displayOrderByColumnId) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateDisplayOrders,
          [displayOrderByColumnId],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> updateStatus(
    String? columnId,
    _i8.RecordStatus? status,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateStatus,
          [
            columnId,
            status,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
}

/// A class which mocks [SheetRowRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSheetRowRepository extends _i1.Mock
    implements _i9.SheetRowRepository {
  @override
  _i6.Future<void> insert(_i4.SheetRow? row) => (super.noSuchMethod(
        Invocation.method(
          #insert,
          [row],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> update(_i4.SheetRow? row) => (super.noSuchMethod(
        Invocation.method(
          #update,
          [row],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i4.SheetRow> findById(String? rowId) => (super.noSuchMethod(
        Invocation.method(
          #findById,
          [rowId],
        ),
        returnValue: _i6.Future<_i4.SheetRow>.value(_FakeSheetRow_2(
          this,
          Invocation.method(
            #findById,
            [rowId],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i4.SheetRow>.value(_FakeSheetRow_2(
          this,
          Invocation.method(
            #findById,
            [rowId],
          ),
        )),
      ) as _i6.Future<_i4.SheetRow>);

  @override
  _i6.Future<int> findMaxRowOrder(String? sheetInstanceId) =>
      (super.noSuchMethod(
        Invocation.method(
          #findMaxRowOrder,
          [sheetInstanceId],
        ),
        returnValue: _i6.Future<int>.value(0),
        returnValueForMissingStub: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);

  @override
  _i6.Future<List<_i4.SheetRow>> findByInstanceId(String? sheetInstanceId) =>
      (super.noSuchMethod(
        Invocation.method(
          #findByInstanceId,
          [sheetInstanceId],
        ),
        returnValue: _i6.Future<List<_i4.SheetRow>>.value(<_i4.SheetRow>[]),
        returnValueForMissingStub:
            _i6.Future<List<_i4.SheetRow>>.value(<_i4.SheetRow>[]),
      ) as _i6.Future<List<_i4.SheetRow>>);
}

/// A class which mocks [SheetCellRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSheetCellRepository extends _i1.Mock
    implements _i10.SheetCellRepository {
  @override
  _i6.Future<_i11.SheetCell?> findByRowAndColumn(
    String? rowId,
    String? columnId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #findByRowAndColumn,
          [
            rowId,
            columnId,
          ],
        ),
        returnValue: _i6.Future<_i11.SheetCell?>.value(),
        returnValueForMissingStub: _i6.Future<_i11.SheetCell?>.value(),
      ) as _i6.Future<_i11.SheetCell?>);

  @override
  _i6.Future<void> insert(_i11.SheetCell? cell) => (super.noSuchMethod(
        Invocation.method(
          #insert,
          [cell],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> update(_i11.SheetCell? cell) => (super.noSuchMethod(
        Invocation.method(
          #update,
          [cell],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<List<_i11.SheetCell>> findByRowId(String? rowId) =>
      (super.noSuchMethod(
        Invocation.method(
          #findByRowId,
          [rowId],
        ),
        returnValue: _i6.Future<List<_i11.SheetCell>>.value(<_i11.SheetCell>[]),
        returnValueForMissingStub:
            _i6.Future<List<_i11.SheetCell>>.value(<_i11.SheetCell>[]),
      ) as _i6.Future<List<_i11.SheetCell>>);

  @override
  _i6.Future<List<_i11.SheetCell>> findByRowIds(List<String>? rowIds) =>
      (super.noSuchMethod(
        Invocation.method(
          #findByRowIds,
          [rowIds],
        ),
        returnValue: _i6.Future<List<_i11.SheetCell>>.value(<_i11.SheetCell>[]),
        returnValueForMissingStub:
            _i6.Future<List<_i11.SheetCell>>.value(<_i11.SheetCell>[]),
      ) as _i6.Future<List<_i11.SheetCell>>);
}
