// Mocks generated by Mockito from annotations
// in m3_pad/test/src/features/voucher/domain/usecases/get_sheet_detail_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i10;

import 'package:m3_pad/src/features/voucher/domain/entities/customer.dart'
    as _i7;
import 'package:m3_pad/src/features/voucher/domain/entities/daily_payment_summary.dart'
    as _i5;
import 'package:m3_pad/src/features/voucher/domain/entities/enums/enums.dart'
    as _i12;
import 'package:m3_pad/src/features/voucher/domain/entities/header.dart' as _i3;
import 'package:m3_pad/src/features/voucher/domain/entities/header_price.dart'
    as _i8;
import 'package:m3_pad/src/features/voucher/domain/entities/sheet_cell.dart'
    as _i15;
import 'package:m3_pad/src/features/voucher/domain/entities/sheet_instance.dart'
    as _i2;
import 'package:m3_pad/src/features/voucher/domain/entities/sheet_row.dart'
    as _i4;
import 'package:m3_pad/src/features/voucher/domain/entities/staff.dart' as _i6;
import 'package:m3_pad/src/features/voucher/domain/entities/staff_shift.dart'
    as _i17;
import 'package:m3_pad/src/features/voucher/domain/repositories/customer_repository.dart'
    as _i20;
import 'package:m3_pad/src/features/voucher/domain/repositories/daily_payment_summary_repository.dart'
    as _i18;
import 'package:m3_pad/src/features/voucher/domain/repositories/header_price_repository.dart'
    as _i21;
import 'package:m3_pad/src/features/voucher/domain/repositories/header_repository.dart'
    as _i11;
import 'package:m3_pad/src/features/voucher/domain/repositories/sheet_cell_repository.dart'
    as _i14;
import 'package:m3_pad/src/features/voucher/domain/repositories/sheet_instance_repository.dart'
    as _i9;
import 'package:m3_pad/src/features/voucher/domain/repositories/sheet_row_repository.dart'
    as _i13;
import 'package:m3_pad/src/features/voucher/domain/repositories/staff_repository.dart'
    as _i19;
import 'package:m3_pad/src/features/voucher/domain/repositories/staff_shift_repository.dart'
    as _i16;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: experimental_member_use
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSheetInstance_0 extends _i1.SmartFake implements _i2.SheetInstance {
  _FakeSheetInstance_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeHeader_1 extends _i1.SmartFake implements _i3.Header {
  _FakeHeader_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSheetRow_2 extends _i1.SmartFake implements _i4.SheetRow {
  _FakeSheetRow_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDailyPaymentSummary_3 extends _i1.SmartFake
    implements _i5.DailyPaymentSummary {
  _FakeDailyPaymentSummary_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStaff_4 extends _i1.SmartFake implements _i6.Staff {
  _FakeStaff_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCustomer_5 extends _i1.SmartFake implements _i7.Customer {
  _FakeCustomer_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeHeaderPrice_6 extends _i1.SmartFake implements _i8.HeaderPrice {
  _FakeHeaderPrice_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SheetInstanceRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSheetInstanceRepository extends _i1.Mock
    implements _i9.SheetInstanceRepository {
  @override
  _i10.Future<void> insert(_i2.SheetInstance? instance) => (super.noSuchMethod(
        Invocation.method(
          #insert,
          [instance],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<_i2.SheetInstance> findById(String? sheetInstanceId) =>
      (super.noSuchMethod(
        Invocation.method(
          #findById,
          [sheetInstanceId],
        ),
        returnValue: _i10.Future<_i2.SheetInstance>.value(_FakeSheetInstance_0(
          this,
          Invocation.method(
            #findById,
            [sheetInstanceId],
          ),
        )),
        returnValueForMissingStub:
            _i10.Future<_i2.SheetInstance>.value(_FakeSheetInstance_0(
          this,
          Invocation.method(
            #findById,
            [sheetInstanceId],
          ),
        )),
      ) as _i10.Future<_i2.SheetInstance>);

  @override
  _i10.Future<_i2.SheetInstance?> findByTemplateAndDate(
    String? sheetTemplateId,
    DateTime? businessDate,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #findByTemplateAndDate,
          [
            sheetTemplateId,
            businessDate,
          ],
        ),
        returnValue: _i10.Future<_i2.SheetInstance?>.value(),
        returnValueForMissingStub: _i10.Future<_i2.SheetInstance?>.value(),
      ) as _i10.Future<_i2.SheetInstance?>);

  @override
  _i10.Future<List<_i2.SheetInstance>> findByTemplateIdAndDateRange(
    String? sheetTemplateId,
    DateTime? from,
    DateTime? to,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #findByTemplateIdAndDateRange,
          [
            sheetTemplateId,
            from,
            to,
          ],
        ),
        returnValue:
            _i10.Future<List<_i2.SheetInstance>>.value(<_i2.SheetInstance>[]),
        returnValueForMissingStub:
            _i10.Future<List<_i2.SheetInstance>>.value(<_i2.SheetInstance>[]),
      ) as _i10.Future<List<_i2.SheetInstance>>);
}

/// A class which mocks [HeaderRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockHeaderRepository extends _i1.Mock implements _i11.HeaderRepository {
  @override
  _i10.Future<void> insert(_i3.Header? header) => (super.noSuchMethod(
        Invocation.method(
          #insert,
          [header],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<_i3.Header> findById(String? columnId) => (super.noSuchMethod(
        Invocation.method(
          #findById,
          [columnId],
        ),
        returnValue: _i10.Future<_i3.Header>.value(_FakeHeader_1(
          this,
          Invocation.method(
            #findById,
            [columnId],
          ),
        )),
        returnValueForMissingStub: _i10.Future<_i3.Header>.value(_FakeHeader_1(
          this,
          Invocation.method(
            #findById,
            [columnId],
          ),
        )),
      ) as _i10.Future<_i3.Header>);

  @override
  _i10.Future<List<_i3.Header>> findByTemplateId(String? sheetTemplateId) =>
      (super.noSuchMethod(
        Invocation.method(
          #findByTemplateId,
          [sheetTemplateId],
        ),
        returnValue: _i10.Future<List<_i3.Header>>.value(<_i3.Header>[]),
        returnValueForMissingStub:
            _i10.Future<List<_i3.Header>>.value(<_i3.Header>[]),
      ) as _i10.Future<List<_i3.Header>>);

  @override
  _i10.Future<void> update(_i3.Header? header) => (super.noSuchMethod(
        Invocation.method(
          #update,
          [header],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> updateDisplayOrders(
          Map<String, int>? displayOrderByColumnId) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateDisplayOrders,
          [displayOrderByColumnId],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> updateStatus(
    String? columnId,
    _i12.RecordStatus? status,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateStatus,
          [
            columnId,
            status,
          ],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);
}

/// A class which mocks [SheetRowRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSheetRowRepository extends _i1.Mock
    implements _i13.SheetRowRepository {
  @override
  _i10.Future<void> insert(_i4.SheetRow? row) => (super.noSuchMethod(
        Invocation.method(
          #insert,
          [row],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> update(_i4.SheetRow? row) => (super.noSuchMethod(
        Invocation.method(
          #update,
          [row],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<_i4.SheetRow> findById(String? rowId) => (super.noSuchMethod(
        Invocation.method(
          #findById,
          [rowId],
        ),
        returnValue: _i10.Future<_i4.SheetRow>.value(_FakeSheetRow_2(
          this,
          Invocation.method(
            #findById,
            [rowId],
          ),
        )),
        returnValueForMissingStub:
            _i10.Future<_i4.SheetRow>.value(_FakeSheetRow_2(
          this,
          Invocation.method(
            #findById,
            [rowId],
          ),
        )),
      ) as _i10.Future<_i4.SheetRow>);

  @override
  _i10.Future<int> findMaxRowOrder(String? sheetInstanceId) =>
      (super.noSuchMethod(
        Invocation.method(
          #findMaxRowOrder,
          [sheetInstanceId],
        ),
        returnValue: _i10.Future<int>.value(0),
        returnValueForMissingStub: _i10.Future<int>.value(0),
      ) as _i10.Future<int>);

  @override
  _i10.Future<List<_i4.SheetRow>> findByInstanceId(String? sheetInstanceId) =>
      (super.noSuchMethod(
        Invocation.method(
          #findByInstanceId,
          [sheetInstanceId],
        ),
        returnValue: _i10.Future<List<_i4.SheetRow>>.value(<_i4.SheetRow>[]),
        returnValueForMissingStub:
            _i10.Future<List<_i4.SheetRow>>.value(<_i4.SheetRow>[]),
      ) as _i10.Future<List<_i4.SheetRow>>);

  @override
  _i10.Future<List<_i4.SheetRow>> findByInstanceIds(
          List<String>? sheetInstanceIds) =>
      (super.noSuchMethod(
        Invocation.method(
          #findByInstanceIds,
          [sheetInstanceIds],
        ),
        returnValue: _i10.Future<List<_i4.SheetRow>>.value(<_i4.SheetRow>[]),
        returnValueForMissingStub:
            _i10.Future<List<_i4.SheetRow>>.value(<_i4.SheetRow>[]),
      ) as _i10.Future<List<_i4.SheetRow>>);

  @override
  _i10.Future<List<String>> findCustomerIdsVisitedBefore(
    List<String>? customerIds,
    DateTime? businessDate,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #findCustomerIdsVisitedBefore,
          [
            customerIds,
            businessDate,
          ],
        ),
        returnValue: _i10.Future<List<String>>.value(<String>[]),
        returnValueForMissingStub: _i10.Future<List<String>>.value(<String>[]),
      ) as _i10.Future<List<String>>);
}

/// A class which mocks [SheetCellRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSheetCellRepository extends _i1.Mock
    implements _i14.SheetCellRepository {
  @override
  _i10.Future<_i15.SheetCell?> findByRowAndColumn(
    String? rowId,
    String? columnId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #findByRowAndColumn,
          [
            rowId,
            columnId,
          ],
        ),
        returnValue: _i10.Future<_i15.SheetCell?>.value(),
        returnValueForMissingStub: _i10.Future<_i15.SheetCell?>.value(),
      ) as _i10.Future<_i15.SheetCell?>);

  @override
  _i10.Future<void> insert(_i15.SheetCell? cell) => (super.noSuchMethod(
        Invocation.method(
          #insert,
          [cell],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> update(_i15.SheetCell? cell) => (super.noSuchMethod(
        Invocation.method(
          #update,
          [cell],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<List<_i15.SheetCell>> findByRowId(String? rowId) =>
      (super.noSuchMethod(
        Invocation.method(
          #findByRowId,
          [rowId],
        ),
        returnValue:
            _i10.Future<List<_i15.SheetCell>>.value(<_i15.SheetCell>[]),
        returnValueForMissingStub:
            _i10.Future<List<_i15.SheetCell>>.value(<_i15.SheetCell>[]),
      ) as _i10.Future<List<_i15.SheetCell>>);

  @override
  _i10.Future<List<_i15.SheetCell>> findByRowIds(List<String>? rowIds) =>
      (super.noSuchMethod(
        Invocation.method(
          #findByRowIds,
          [rowIds],
        ),
        returnValue:
            _i10.Future<List<_i15.SheetCell>>.value(<_i15.SheetCell>[]),
        returnValueForMissingStub:
            _i10.Future<List<_i15.SheetCell>>.value(<_i15.SheetCell>[]),
      ) as _i10.Future<List<_i15.SheetCell>>);
}

/// A class which mocks [StaffShiftRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockStaffShiftRepository extends _i1.Mock
    implements _i16.StaffShiftRepository {
  @override
  _i10.Future<void> insert(_i17.StaffShift? shift) => (super.noSuchMethod(
        Invocation.method(
          #insert,
          [shift],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> update(_i17.StaffShift? shift) => (super.noSuchMethod(
        Invocation.method(
          #update,
          [shift],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<List<_i17.StaffShift>> findByInstanceId(
          String? sheetInstanceId) =>
      (super.noSuchMethod(
        Invocation.method(
          #findByInstanceId,
          [sheetInstanceId],
        ),
        returnValue:
            _i10.Future<List<_i17.StaffShift>>.value(<_i17.StaffShift>[]),
        returnValueForMissingStub:
            _i10.Future<List<_i17.StaffShift>>.value(<_i17.StaffShift>[]),
      ) as _i10.Future<List<_i17.StaffShift>>);
}

/// A class which mocks [DailyPaymentSummaryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDailyPaymentSummaryRepository extends _i1.Mock
    implements _i18.DailyPaymentSummaryRepository {
  @override
  _i10.Future<_i5.DailyPaymentSummary> getByInstanceId(
    String? sheetInstanceId,
    DateTime? businessDate,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getByInstanceId,
          [
            sheetInstanceId,
            businessDate,
          ],
        ),
        returnValue: _i10.Future<_i5.DailyPaymentSummary>.value(
            _FakeDailyPaymentSummary_3(
          this,
          Invocation.method(
            #getByInstanceId,
            [
              sheetInstanceId,
              businessDate,
            ],
          ),
        )),
        returnValueForMissingStub: _i10.Future<_i5.DailyPaymentSummary>.value(
            _FakeDailyPaymentSummary_3(
          this,
          Invocation.method(
            #getByInstanceId,
            [
              sheetInstanceId,
              businessDate,
            ],
          ),
        )),
      ) as _i10.Future<_i5.DailyPaymentSummary>);
}

/// A class which mocks [StaffRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockStaffRepository extends _i1.Mock implements _i19.StaffRepository {
  @override
  _i10.Future<void> insert(_i6.Staff? staff) => (super.noSuchMethod(
        Invocation.method(
          #insert,
          [staff],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<_i6.Staff> findById(String? staffId) => (super.noSuchMethod(
        Invocation.method(
          #findById,
          [staffId],
        ),
        returnValue: _i10.Future<_i6.Staff>.value(_FakeStaff_4(
          this,
          Invocation.method(
            #findById,
            [staffId],
          ),
        )),
        returnValueForMissingStub: _i10.Future<_i6.Staff>.value(_FakeStaff_4(
          this,
          Invocation.method(
            #findById,
            [staffId],
          ),
        )),
      ) as _i10.Future<_i6.Staff>);

  @override
  _i10.Future<List<_i6.Staff>> findAllActive() => (super.noSuchMethod(
        Invocation.method(
          #findAllActive,
          [],
        ),
        returnValue: _i10.Future<List<_i6.Staff>>.value(<_i6.Staff>[]),
        returnValueForMissingStub:
            _i10.Future<List<_i6.Staff>>.value(<_i6.Staff>[]),
      ) as _i10.Future<List<_i6.Staff>>);

  @override
  _i10.Future<_i6.Staff?> findByName(String? name) => (super.noSuchMethod(
        Invocation.method(
          #findByName,
          [name],
        ),
        returnValue: _i10.Future<_i6.Staff?>.value(),
        returnValueForMissingStub: _i10.Future<_i6.Staff?>.value(),
      ) as _i10.Future<_i6.Staff?>);

  @override
  _i10.Future<void> updateName(
    String? staffId,
    String? name,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateName,
          [
            staffId,
            name,
          ],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> updateStatus(
    String? staffId,
    _i12.RecordStatus? status,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateStatus,
          [
            staffId,
            status,
          ],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);
}

/// A class which mocks [CustomerRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCustomerRepository extends _i1.Mock
    implements _i20.CustomerRepository {
  @override
  _i10.Future<void> insert(_i7.Customer? customer) => (super.noSuchMethod(
        Invocation.method(
          #insert,
          [customer],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<_i7.Customer> findById(String? customerId) => (super.noSuchMethod(
        Invocation.method(
          #findById,
          [customerId],
        ),
        returnValue: _i10.Future<_i7.Customer>.value(_FakeCustomer_5(
          this,
          Invocation.method(
            #findById,
            [customerId],
          ),
        )),
        returnValueForMissingStub:
            _i10.Future<_i7.Customer>.value(_FakeCustomer_5(
          this,
          Invocation.method(
            #findById,
            [customerId],
          ),
        )),
      ) as _i10.Future<_i7.Customer>);

  @override
  _i10.Future<List<_i7.Customer>> findByIds(List<String>? customerIds) =>
      (super.noSuchMethod(
        Invocation.method(
          #findByIds,
          [customerIds],
        ),
        returnValue: _i10.Future<List<_i7.Customer>>.value(<_i7.Customer>[]),
        returnValueForMissingStub:
            _i10.Future<List<_i7.Customer>>.value(<_i7.Customer>[]),
      ) as _i10.Future<List<_i7.Customer>>);

  @override
  _i10.Future<_i7.Customer?> findByName(String? name) => (super.noSuchMethod(
        Invocation.method(
          #findByName,
          [name],
        ),
        returnValue: _i10.Future<_i7.Customer?>.value(),
        returnValueForMissingStub: _i10.Future<_i7.Customer?>.value(),
      ) as _i10.Future<_i7.Customer?>);
}

/// A class which mocks [HeaderPriceRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockHeaderPriceRepository extends _i1.Mock
    implements _i21.HeaderPriceRepository {
  @override
  _i10.Future<void> insert(_i8.HeaderPrice? headerPrice) => (super.noSuchMethod(
        Invocation.method(
          #insert,
          [headerPrice],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<_i8.HeaderPrice> findCurrentPrice(
    String? columnId,
    DateTime? targetDate,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #findCurrentPrice,
          [
            columnId,
            targetDate,
          ],
        ),
        returnValue: _i10.Future<_i8.HeaderPrice>.value(_FakeHeaderPrice_6(
          this,
          Invocation.method(
            #findCurrentPrice,
            [
              columnId,
              targetDate,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i10.Future<_i8.HeaderPrice>.value(_FakeHeaderPrice_6(
          this,
          Invocation.method(
            #findCurrentPrice,
            [
              columnId,
              targetDate,
            ],
          ),
        )),
      ) as _i10.Future<_i8.HeaderPrice>);

  @override
  _i10.Future<List<_i8.HeaderPrice>> findCurrentPrices(
    List<String>? columnIds,
    DateTime? targetDate,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #findCurrentPrices,
          [
            columnIds,
            targetDate,
          ],
        ),
        returnValue:
            _i10.Future<List<_i8.HeaderPrice>>.value(<_i8.HeaderPrice>[]),
        returnValueForMissingStub:
            _i10.Future<List<_i8.HeaderPrice>>.value(<_i8.HeaderPrice>[]),
      ) as _i10.Future<List<_i8.HeaderPrice>>);

  @override
  _i10.Future<void> closeCurrentPrice(
    String? priceId,
    DateTime? effectiveTo,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #closeCurrentPrice,
          [
            priceId,
            effectiveTo,
          ],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);
}
