// Mocks generated by Mockito from annotations
// in m3_pad/test/src/features/voucher/domain/usecases/input_cell_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i7;

import 'package:m3_pad/src/core/utils/id_generator.dart' as _i14;
import 'package:m3_pad/src/features/voucher/domain/entities/enums/enums.dart'
    as _i10;
import 'package:m3_pad/src/features/voucher/domain/entities/header.dart' as _i4;
import 'package:m3_pad/src/features/voucher/domain/entities/header_price.dart'
    as _i5;
import 'package:m3_pad/src/features/voucher/domain/entities/sheet_cell.dart'
    as _i13;
import 'package:m3_pad/src/features/voucher/domain/entities/sheet_instance.dart'
    as _i3;
import 'package:m3_pad/src/features/voucher/domain/entities/sheet_row.dart'
    as _i2;
import 'package:m3_pad/src/features/voucher/domain/repositories/header_price_repository.dart'
    as _i11;
import 'package:m3_pad/src/features/voucher/domain/repositories/header_repository.dart'
    as _i9;
import 'package:m3_pad/src/features/voucher/domain/repositories/sheet_cell_repository.dart'
    as _i12;
import 'package:m3_pad/src/features/voucher/domain/repositories/sheet_instance_repository.dart'
    as _i8;
import 'package:m3_pad/src/features/voucher/domain/repositories/sheet_row_repository.dart'
    as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i15;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: experimental_member_use
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSheetRow_0 extends _i1.SmartFake implements _i2.SheetRow {
  _FakeSheetRow_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSheetInstance_1 extends _i1.SmartFake implements _i3.SheetInstance {
  _FakeSheetInstance_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeHeader_2 extends _i1.SmartFake implements _i4.Header {
  _FakeHeader_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeHeaderPrice_3 extends _i1.SmartFake implements _i5.HeaderPrice {
  _FakeHeaderPrice_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SheetRowRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSheetRowRepository extends _i1.Mock
    implements _i6.SheetRowRepository {
  @override
  _i7.Future<void> insert(_i2.SheetRow? row) => (super.noSuchMethod(
        Invocation.method(
          #insert,
          [row],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> update(_i2.SheetRow? row) => (super.noSuchMethod(
        Invocation.method(
          #update,
          [row],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<_i2.SheetRow> findById(String? rowId) => (super.noSuchMethod(
        Invocation.method(
          #findById,
          [rowId],
        ),
        returnValue: _i7.Future<_i2.SheetRow>.value(_FakeSheetRow_0(
          this,
          Invocation.method(
            #findById,
            [rowId],
          ),
        )),
        returnValueForMissingStub:
            _i7.Future<_i2.SheetRow>.value(_FakeSheetRow_0(
          this,
          Invocation.method(
            #findById,
            [rowId],
          ),
        )),
      ) as _i7.Future<_i2.SheetRow>);

  @override
  _i7.Future<int> findMaxRowOrder(String? sheetInstanceId) =>
      (super.noSuchMethod(
        Invocation.method(
          #findMaxRowOrder,
          [sheetInstanceId],
        ),
        returnValue: _i7.Future<int>.value(0),
        returnValueForMissingStub: _i7.Future<int>.value(0),
      ) as _i7.Future<int>);

  @override
  _i7.Future<List<_i2.SheetRow>> findByInstanceId(String? sheetInstanceId) =>
      (super.noSuchMethod(
        Invocation.method(
          #findByInstanceId,
          [sheetInstanceId],
        ),
        returnValue: _i7.Future<List<_i2.SheetRow>>.value(<_i2.SheetRow>[]),
        returnValueForMissingStub:
            _i7.Future<List<_i2.SheetRow>>.value(<_i2.SheetRow>[]),
      ) as _i7.Future<List<_i2.SheetRow>>);

  @override
  _i7.Future<List<_i2.SheetRow>> findByInstanceIds(
          List<String>? sheetInstanceIds) =>
      (super.noSuchMethod(
        Invocation.method(
          #findByInstanceIds,
          [sheetInstanceIds],
        ),
        returnValue: _i7.Future<List<_i2.SheetRow>>.value(<_i2.SheetRow>[]),
        returnValueForMissingStub:
            _i7.Future<List<_i2.SheetRow>>.value(<_i2.SheetRow>[]),
      ) as _i7.Future<List<_i2.SheetRow>>);
}

/// A class which mocks [SheetInstanceRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSheetInstanceRepository extends _i1.Mock
    implements _i8.SheetInstanceRepository {
  @override
  _i7.Future<void> insert(_i3.SheetInstance? instance) => (super.noSuchMethod(
        Invocation.method(
          #insert,
          [instance],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<_i3.SheetInstance> findById(String? sheetInstanceId) =>
      (super.noSuchMethod(
        Invocation.method(
          #findById,
          [sheetInstanceId],
        ),
        returnValue: _i7.Future<_i3.SheetInstance>.value(_FakeSheetInstance_1(
          this,
          Invocation.method(
            #findById,
            [sheetInstanceId],
          ),
        )),
        returnValueForMissingStub:
            _i7.Future<_i3.SheetInstance>.value(_FakeSheetInstance_1(
          this,
          Invocation.method(
            #findById,
            [sheetInstanceId],
          ),
        )),
      ) as _i7.Future<_i3.SheetInstance>);

  @override
  _i7.Future<_i3.SheetInstance?> findByTemplateAndDate(
    String? sheetTemplateId,
    DateTime? businessDate,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #findByTemplateAndDate,
          [
            sheetTemplateId,
            businessDate,
          ],
        ),
        returnValue: _i7.Future<_i3.SheetInstance?>.value(),
        returnValueForMissingStub: _i7.Future<_i3.SheetInstance?>.value(),
      ) as _i7.Future<_i3.SheetInstance?>);

  @override
  _i7.Future<List<_i3.SheetInstance>> findByTemplateIdAndDateRange(
    String? sheetTemplateId,
    DateTime? from,
    DateTime? to,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #findByTemplateIdAndDateRange,
          [
            sheetTemplateId,
            from,
            to,
          ],
        ),
        returnValue:
            _i7.Future<List<_i3.SheetInstance>>.value(<_i3.SheetInstance>[]),
        returnValueForMissingStub:
            _i7.Future<List<_i3.SheetInstance>>.value(<_i3.SheetInstance>[]),
      ) as _i7.Future<List<_i3.SheetInstance>>);
}

/// A class which mocks [HeaderRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockHeaderRepository extends _i1.Mock implements _i9.HeaderRepository {
  @override
  _i7.Future<void> insert(_i4.Header? header) => (super.noSuchMethod(
        Invocation.method(
          #insert,
          [header],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<_i4.Header> findById(String? columnId) => (super.noSuchMethod(
        Invocation.method(
          #findById,
          [columnId],
        ),
        returnValue: _i7.Future<_i4.Header>.value(_FakeHeader_2(
          this,
          Invocation.method(
            #findById,
            [columnId],
          ),
        )),
        returnValueForMissingStub: _i7.Future<_i4.Header>.value(_FakeHeader_2(
          this,
          Invocation.method(
            #findById,
            [columnId],
          ),
        )),
      ) as _i7.Future<_i4.Header>);

  @override
  _i7.Future<List<_i4.Header>> findByTemplateId(String? sheetTemplateId) =>
      (super.noSuchMethod(
        Invocation.method(
          #findByTemplateId,
          [sheetTemplateId],
        ),
        returnValue: _i7.Future<List<_i4.Header>>.value(<_i4.Header>[]),
        returnValueForMissingStub:
            _i7.Future<List<_i4.Header>>.value(<_i4.Header>[]),
      ) as _i7.Future<List<_i4.Header>>);

  @override
  _i7.Future<void> update(_i4.Header? header) => (super.noSuchMethod(
        Invocation.method(
          #update,
          [header],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> updateDisplayOrders(
          Map<String, int>? displayOrderByColumnId) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateDisplayOrders,
          [displayOrderByColumnId],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> updateStatus(
    String? columnId,
    _i10.RecordStatus? status,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateStatus,
          [
            columnId,
            status,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
}

/// A class which mocks [HeaderPriceRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockHeaderPriceRepository extends _i1.Mock
    implements _i11.HeaderPriceRepository {
  @override
  _i7.Future<void> insert(_i5.HeaderPrice? headerPrice) => (super.noSuchMethod(
        Invocation.method(
          #insert,
          [headerPrice],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<_i5.HeaderPrice> findCurrentPrice(
    String? columnId,
    DateTime? targetDate,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #findCurrentPrice,
          [
            columnId,
            targetDate,
          ],
        ),
        returnValue: _i7.Future<_i5.HeaderPrice>.value(_FakeHeaderPrice_3(
          this,
          Invocation.method(
            #findCurrentPrice,
            [
              columnId,
              targetDate,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i7.Future<_i5.HeaderPrice>.value(_FakeHeaderPrice_3(
          this,
          Invocation.method(
            #findCurrentPrice,
            [
              columnId,
              targetDate,
            ],
          ),
        )),
      ) as _i7.Future<_i5.HeaderPrice>);

  @override
  _i7.Future<List<_i5.HeaderPrice>> findCurrentPrices(
    List<String>? columnIds,
    DateTime? targetDate,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #findCurrentPrices,
          [
            columnIds,
            targetDate,
          ],
        ),
        returnValue:
            _i7.Future<List<_i5.HeaderPrice>>.value(<_i5.HeaderPrice>[]),
        returnValueForMissingStub:
            _i7.Future<List<_i5.HeaderPrice>>.value(<_i5.HeaderPrice>[]),
      ) as _i7.Future<List<_i5.HeaderPrice>>);

  @override
  _i7.Future<void> closeCurrentPrice(
    String? priceId,
    DateTime? effectiveTo,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #closeCurrentPrice,
          [
            priceId,
            effectiveTo,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
}

/// A class which mocks [SheetCellRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSheetCellRepository extends _i1.Mock
    implements _i12.SheetCellRepository {
  @override
  _i7.Future<_i13.SheetCell?> findByRowAndColumn(
    String? rowId,
    String? columnId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #findByRowAndColumn,
          [
            rowId,
            columnId,
          ],
        ),
        returnValue: _i7.Future<_i13.SheetCell?>.value(),
        returnValueForMissingStub: _i7.Future<_i13.SheetCell?>.value(),
      ) as _i7.Future<_i13.SheetCell?>);

  @override
  _i7.Future<void> insert(_i13.SheetCell? cell) => (super.noSuchMethod(
        Invocation.method(
          #insert,
          [cell],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> update(_i13.SheetCell? cell) => (super.noSuchMethod(
        Invocation.method(
          #update,
          [cell],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<List<_i13.SheetCell>> findByRowId(String? rowId) =>
      (super.noSuchMethod(
        Invocation.method(
          #findByRowId,
          [rowId],
        ),
        returnValue: _i7.Future<List<_i13.SheetCell>>.value(<_i13.SheetCell>[]),
        returnValueForMissingStub:
            _i7.Future<List<_i13.SheetCell>>.value(<_i13.SheetCell>[]),
      ) as _i7.Future<List<_i13.SheetCell>>);

  @override
  _i7.Future<List<_i13.SheetCell>> findByRowIds(List<String>? rowIds) =>
      (super.noSuchMethod(
        Invocation.method(
          #findByRowIds,
          [rowIds],
        ),
        returnValue: _i7.Future<List<_i13.SheetCell>>.value(<_i13.SheetCell>[]),
        returnValueForMissingStub:
            _i7.Future<List<_i13.SheetCell>>.value(<_i13.SheetCell>[]),
      ) as _i7.Future<List<_i13.SheetCell>>);
}

/// A class which mocks [IdGenerator].
///
/// See the documentation for Mockito's code generation for more information.
class MockIdGenerator extends _i1.Mock implements _i14.IdGenerator {
  @override
  String generate() => (super.noSuchMethod(
        Invocation.method(
          #generate,
          [],
        ),
        returnValue: _i15.dummyValue<String>(
          this,
          Invocation.method(
            #generate,
            [],
          ),
        ),
        returnValueForMissingStub: _i15.dummyValue<String>(
          this,
          Invocation.method(
            #generate,
            [],
          ),
        ),
      ) as String);
}
