// Mocks generated by Mockito from annotations
// in m3_pad/test/src/features/voucher/domain/usecases/update_row_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i5;

import 'package:m3_pad/src/core/utils/id_generator.dart' as _i7;
import 'package:m3_pad/src/features/voucher/domain/entities/customer.dart'
    as _i3;
import 'package:m3_pad/src/features/voucher/domain/entities/sheet_row.dart'
    as _i2;
import 'package:m3_pad/src/features/voucher/domain/repositories/customer_repository.dart'
    as _i6;
import 'package:m3_pad/src/features/voucher/domain/repositories/sheet_row_repository.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: experimental_member_use
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSheetRow_0 extends _i1.SmartFake implements _i2.SheetRow {
  _FakeSheetRow_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCustomer_1 extends _i1.SmartFake implements _i3.Customer {
  _FakeCustomer_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SheetRowRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSheetRowRepository extends _i1.Mock
    implements _i4.SheetRowRepository {
  @override
  _i5.Future<void> insert(_i2.SheetRow? row) => (super.noSuchMethod(
        Invocation.method(
          #insert,
          [row],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> update(_i2.SheetRow? row) => (super.noSuchMethod(
        Invocation.method(
          #update,
          [row],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i2.SheetRow> findById(String? rowId) => (super.noSuchMethod(
        Invocation.method(
          #findById,
          [rowId],
        ),
        returnValue: _i5.Future<_i2.SheetRow>.value(_FakeSheetRow_0(
          this,
          Invocation.method(
            #findById,
            [rowId],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i2.SheetRow>.value(_FakeSheetRow_0(
          this,
          Invocation.method(
            #findById,
            [rowId],
          ),
        )),
      ) as _i5.Future<_i2.SheetRow>);

  @override
  _i5.Future<int> findMaxRowOrder(String? sheetInstanceId) =>
      (super.noSuchMethod(
        Invocation.method(
          #findMaxRowOrder,
          [sheetInstanceId],
        ),
        returnValue: _i5.Future<int>.value(0),
        returnValueForMissingStub: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<List<_i2.SheetRow>> findByInstanceId(String? sheetInstanceId) =>
      (super.noSuchMethod(
        Invocation.method(
          #findByInstanceId,
          [sheetInstanceId],
        ),
        returnValue: _i5.Future<List<_i2.SheetRow>>.value(<_i2.SheetRow>[]),
        returnValueForMissingStub:
            _i5.Future<List<_i2.SheetRow>>.value(<_i2.SheetRow>[]),
      ) as _i5.Future<List<_i2.SheetRow>>);

  @override
  _i5.Future<List<_i2.SheetRow>> findByInstanceIds(
          List<String>? sheetInstanceIds) =>
      (super.noSuchMethod(
        Invocation.method(
          #findByInstanceIds,
          [sheetInstanceIds],
        ),
        returnValue: _i5.Future<List<_i2.SheetRow>>.value(<_i2.SheetRow>[]),
        returnValueForMissingStub:
            _i5.Future<List<_i2.SheetRow>>.value(<_i2.SheetRow>[]),
      ) as _i5.Future<List<_i2.SheetRow>>);
}

/// A class which mocks [CustomerRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCustomerRepository extends _i1.Mock
    implements _i6.CustomerRepository {
  @override
  _i5.Future<void> insert(_i3.Customer? customer) => (super.noSuchMethod(
        Invocation.method(
          #insert,
          [customer],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i3.Customer> findById(String? customerId) => (super.noSuchMethod(
        Invocation.method(
          #findById,
          [customerId],
        ),
        returnValue: _i5.Future<_i3.Customer>.value(_FakeCustomer_1(
          this,
          Invocation.method(
            #findById,
            [customerId],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.Customer>.value(_FakeCustomer_1(
          this,
          Invocation.method(
            #findById,
            [customerId],
          ),
        )),
      ) as _i5.Future<_i3.Customer>);

  @override
  _i5.Future<List<_i3.Customer>> findByIds(List<String>? customerIds) =>
      (super.noSuchMethod(
        Invocation.method(
          #findByIds,
          [customerIds],
        ),
        returnValue: _i5.Future<List<_i3.Customer>>.value(<_i3.Customer>[]),
        returnValueForMissingStub:
            _i5.Future<List<_i3.Customer>>.value(<_i3.Customer>[]),
      ) as _i5.Future<List<_i3.Customer>>);

  @override
  _i5.Future<_i3.Customer?> findByName(String? name) => (super.noSuchMethod(
        Invocation.method(
          #findByName,
          [name],
        ),
        returnValue: _i5.Future<_i3.Customer?>.value(),
        returnValueForMissingStub: _i5.Future<_i3.Customer?>.value(),
      ) as _i5.Future<_i3.Customer?>);
}

/// A class which mocks [IdGenerator].
///
/// See the documentation for Mockito's code generation for more information.
class MockIdGenerator extends _i1.Mock implements _i7.IdGenerator {
  @override
  String generate() => (super.noSuchMethod(
        Invocation.method(
          #generate,
          [],
        ),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.method(
            #generate,
            [],
          ),
        ),
        returnValueForMissingStub: _i8.dummyValue<String>(
          this,
          Invocation.method(
            #generate,
            [],
          ),
        ),
      ) as String);
}
