// Mocks generated by Mockito from annotations
// in m3_pad/test/src/features/voucher/domain/usecases/update_header_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i5;

import 'package:m3_pad/src/core/utils/id_generator.dart' as _i8;
import 'package:m3_pad/src/features/voucher/domain/entities/enums/enums.dart'
    as _i6;
import 'package:m3_pad/src/features/voucher/domain/entities/header.dart' as _i2;
import 'package:m3_pad/src/features/voucher/domain/entities/header_price.dart'
    as _i3;
import 'package:m3_pad/src/features/voucher/domain/repositories/header_price_repository.dart'
    as _i7;
import 'package:m3_pad/src/features/voucher/domain/repositories/header_repository.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: experimental_member_use
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeHeader_0 extends _i1.SmartFake implements _i2.Header {
  _FakeHeader_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeHeaderPrice_1 extends _i1.SmartFake implements _i3.HeaderPrice {
  _FakeHeaderPrice_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [HeaderRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockHeaderRepository extends _i1.Mock implements _i4.HeaderRepository {
  @override
  _i5.Future<void> insert(_i2.Header? header) => (super.noSuchMethod(
        Invocation.method(
          #insert,
          [header],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i2.Header> findById(String? columnId) => (super.noSuchMethod(
        Invocation.method(
          #findById,
          [columnId],
        ),
        returnValue: _i5.Future<_i2.Header>.value(_FakeHeader_0(
          this,
          Invocation.method(
            #findById,
            [columnId],
          ),
        )),
        returnValueForMissingStub: _i5.Future<_i2.Header>.value(_FakeHeader_0(
          this,
          Invocation.method(
            #findById,
            [columnId],
          ),
        )),
      ) as _i5.Future<_i2.Header>);

  @override
  _i5.Future<List<_i2.Header>> findByTemplateId(String? sheetTemplateId) =>
      (super.noSuchMethod(
        Invocation.method(
          #findByTemplateId,
          [sheetTemplateId],
        ),
        returnValue: _i5.Future<List<_i2.Header>>.value(<_i2.Header>[]),
        returnValueForMissingStub:
            _i5.Future<List<_i2.Header>>.value(<_i2.Header>[]),
      ) as _i5.Future<List<_i2.Header>>);

  @override
  _i5.Future<void> update(_i2.Header? header) => (super.noSuchMethod(
        Invocation.method(
          #update,
          [header],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateDisplayOrders(
          Map<String, int>? displayOrderByColumnId) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateDisplayOrders,
          [displayOrderByColumnId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateStatus(
    String? columnId,
    _i6.RecordStatus? status,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateStatus,
          [
            columnId,
            status,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [HeaderPriceRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockHeaderPriceRepository extends _i1.Mock
    implements _i7.HeaderPriceRepository {
  @override
  _i5.Future<void> insert(_i3.HeaderPrice? headerPrice) => (super.noSuchMethod(
        Invocation.method(
          #insert,
          [headerPrice],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i3.HeaderPrice> findCurrentPrice(
    String? columnId,
    DateTime? targetDate,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #findCurrentPrice,
          [
            columnId,
            targetDate,
          ],
        ),
        returnValue: _i5.Future<_i3.HeaderPrice>.value(_FakeHeaderPrice_1(
          this,
          Invocation.method(
            #findCurrentPrice,
            [
              columnId,
              targetDate,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.HeaderPrice>.value(_FakeHeaderPrice_1(
          this,
          Invocation.method(
            #findCurrentPrice,
            [
              columnId,
              targetDate,
            ],
          ),
        )),
      ) as _i5.Future<_i3.HeaderPrice>);

  @override
  _i5.Future<List<_i3.HeaderPrice>> findCurrentPrices(
    List<String>? columnIds,
    DateTime? targetDate,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #findCurrentPrices,
          [
            columnIds,
            targetDate,
          ],
        ),
        returnValue:
            _i5.Future<List<_i3.HeaderPrice>>.value(<_i3.HeaderPrice>[]),
        returnValueForMissingStub:
            _i5.Future<List<_i3.HeaderPrice>>.value(<_i3.HeaderPrice>[]),
      ) as _i5.Future<List<_i3.HeaderPrice>>);

  @override
  _i5.Future<void> closeCurrentPrice(
    String? priceId,
    DateTime? effectiveTo,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #closeCurrentPrice,
          [
            priceId,
            effectiveTo,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [IdGenerator].
///
/// See the documentation for Mockito's code generation for more information.
class MockIdGenerator extends _i1.Mock implements _i8.IdGenerator {
  @override
  String generate() => (super.noSuchMethod(
        Invocation.method(
          #generate,
          [],
        ),
        returnValue: _i9.dummyValue<String>(
          this,
          Invocation.method(
            #generate,
            [],
          ),
        ),
        returnValueForMissingStub: _i9.dummyValue<String>(
          this,
          Invocation.method(
            #generate,
            [],
          ),
        ),
      ) as String);
}
